# Pandas By Code With Harry Crash Course

In [2]:
import pandas as pd

### Basic Data Structures of pandas
* Series (Labeled & Unlabeled)
* DataFrame

1. Unlabeled Series Data Structure

In [3]:
unlabeled = pd.Series([1 , 2 , 3 , 4 , 5])
unlabeled

0    1
1    2
2    3
3    4
4    5
dtype: int64

2. Labeled Series Data Structure

In [4]:
labeled = pd.Series([1 , 2 , 3 , 4 , 5], index=['a', 'b', 'c', 'd', 'e'])
labeled

a    1
b    2
c    3
d    4
e    5
dtype: int64

DataFrame Structure

In [5]:
dataFrame = pd.DataFrame({"name":["Gojo" , "Geto" , "Shoko"], "marks":[100 , 90 , 80]}, index=['a', 'b', 'c'])
dataFrame

    name  marks
a   Gojo    100
b   Geto     90
c  Shoko     80

### ```.csv``` files read

In [7]:
data = pd.read_csv('./data/customers-1000.csv')
data

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,FbcCaF483aFaFAE,Diana,Monroe,Bass-Wilson,Lake Jacksonmouth,Guatemala,+1-171-715-9766x54993,(489)413-7296x32807,cassidymercado@bonilla.com,2022-01-09,http://castro.net/
996,997,979c4D58Ae9a9cc,Jerry,Morales,Pratt-King,South Dominiquemouth,Georgia,132.253.8501x097,+1-301-292-8363x80270,gavin13@logan-downs.com,2021-08-21,https://www.braun.info/
997,998,D0DcF6a4BcefCc8,Tracie,Floyd,"Holt, Wilson and Shields",East Chloeshire,Solomon Islands,1193982387,(482)926-8966,lowehailey@oconnor.org,2020-04-22,http://www.zavala-rubio.com/
998,999,90EE9CbbDa374E9,Paul,Barnes,"Brown, Oliver and Haynes",South Shane,Finland,+1-537-466-3245x3699,791-835-9075,hodgeseddie@hardin-wells.com,2021-03-12,https://stone-randolph.info/
999,1000,51732B5b2328015,Dominic,Duran,Durham LLC,East Wendy,British Indian Ocean Territory (Chagos Archipe...,+1-278-758-4331,814-860-0941x057,owarner@velasquez.info,2021-12-09,http://www.cox.com/

### Useful Functions
1. ```head()```
2. ```tail()```
3. ```describe()```
4. ```info()```

In [8]:
data.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/

In [9]:
data.tail()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
995,996,FbcCaF483aFaFAE,Diana,Monroe,Bass-Wilson,Lake Jacksonmouth,Guatemala,+1-171-715-9766x54993,(489)413-7296x32807,cassidymercado@bonilla.com,2022-01-09,http://castro.net/
996,997,979c4D58Ae9a9cc,Jerry,Morales,Pratt-King,South Dominiquemouth,Georgia,132.253.8501x097,+1-301-292-8363x80270,gavin13@logan-downs.com,2021-08-21,https://www.braun.info/
997,998,D0DcF6a4BcefCc8,Tracie,Floyd,"Holt, Wilson and Shields",East Chloeshire,Solomon Islands,1193982387,(482)926-8966,lowehailey@oconnor.org,2020-04-22,http://www.zavala-rubio.com/
998,999,90EE9CbbDa374E9,Paul,Barnes,"Brown, Oliver and Haynes",South Shane,Finland,+1-537-466-3245x3699,791-835-9075,hodgeseddie@hardin-wells.com,2021-03-12,https://stone-randolph.info/
999,1000,51732B5b2328015,Dominic,Duran,Durham LLC,East Wendy,British Indian Ocean Territory (Chagos Archipe...,+1-278-758-4331,814-860-0941x057,owarner@velasquez.info,2021-12-09,http://www.cox.com/

In [10]:
data.describe()

             Index
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              1000 non-null   int64
 1   Customer Id        1000 non-null   object
 2   First Name         1000 non-null   object
 3   Last Name          1000 non-null   object
 4   Company            1000 non-null   object
 5   City               1000 non-null   object
 6   Country            1000 non-null   object
 7   Phone 1            1000 non-null   object
 8   Phone 2            1000 non-null   object
 9   Email              1000 non-null   object
 10  Subscription Date  1000 non-null   object
 11  Website            1000 non-null   object
dtypes: int64(1), object(11)
memory usage: 93.9+ KB

### Data Selection
When want a particular type of data <br>
e.g
1. IDs from the file only
2. Names fo the file only
3. Or multiple Type of data but not everything

In [12]:
# For Single Data Selection
data["Customer Id"]

0      dE014d010c7ab0c
1      2B54172c8b65eC3
2      d794Dd48988d2ac
3      3b3Aa4aCc68f3Be
4      D60df62ad2ae41E
            ...
995    FbcCaF483aFaFAE
996    979c4D58Ae9a9cc
997    D0DcF6a4BcefCc8
998    90EE9CbbDa374E9
999    51732B5b2328015
Name: Customer Id, Length: 1000, dtype: object

In [13]:
# For Multiple Data Selection
data[["First Name", "Last Name"]]

    First Name Last Name
0       Andrew   Goodman
1        Alvin      Lane
2        Jenna   Harding
3     Fernando      Ford
4         Kara     Woods
..         ...       ...
995      Diana    Monroe
996      Jerry   Morales
997     Tracie     Floyd
998       Paul    Barnes
999    Dominic     Duran

[1000 rows x 2 columns]

In [14]:
# When to iterate row-wise Data suppose the 2nd iterated row or 3rd row
data.iloc[2]

Index                                          3
Customer Id                      d794Dd48988d2ac
First Name                                 Jenna
Last Name                                Harding
Company                             Bailey Group
City                                Moniquemouth
Country                                    China
Phone 1                       (335)987-3085x3780
Phone 2                         001-680-204-8312
Email                    justincurtis@pierce.org
Subscription Date                     2020-04-05
Website              http://www.booth-reese.biz/
Name: 2, dtype: object

### ```type()``` Function

In [15]:
type(data.iloc[2])

pandas.core.series.Series

In [16]:
type(data.describe())

pandas.core.frame.DataFrame

In [17]:
type(data["Customer Id"])

pandas.core.series.Series

In [18]:
type(data[["First Name", "Last Name"]])

pandas.core.frame.DataFrame

### Editing Methods in ```.csv``` file
1. ```dropna()``` function : To avoid rows which does not have any information like the email or DOB
* Syntax : ```dropna()```
2. ```fillna(data)``` function: To add data which will be filled in blank spaces <br>
* Syntax: ```fillna(N.A. , inplace = True)``` --> Here ```inplace = True``` is not recommended as it will make changes in Original Data Set or in ```.csv``` file
3. ```rename()``` function : Used to rename any column name. Here also ```inplace = True``` is used but do not use unconsciously otherwise Original Data will be changed

In [20]:
people = pd.read_csv('./data/people-100.csv')
people.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,NaN,bethany14@example.com,214.112.6044x4913,24-03-1910,NaN
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher
4,5,1bA7A3dc874da3c,Lori,NaN,Male,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon

In [46]:
people[people["Sex"]=="Male"]["Email"]

0             elijah57@example.net
2            bthompson@example.com
3        kaitlinkaiser@example.com
4       buchananmanuel@example.net
5              tconner@example.org
7          wyattbishop@example.com
8              nmccann@example.net
9      virginiaterrell@example.org
11            rayleroy@example.org
12        jefferynoble@example.org
14            pmiranda@example.org
16         sheenabanks@example.com
17             gbrewer@example.org
18    gilbertdonaldson@example.com
22           huangbill@example.org
25         sallymiller@example.net
26           bsullivan@example.net
28            irosales@example.net
29             mconrad@example.com
31            nsampson@example.net
35           jeannovak@example.org
36           clinton78@example.org
44          lhernandez@example.com
47         erikmueller@example.org
48      rivasdominique@example.org
49          daisymcgee@example.net
59        clarkeangela@example.net
60           kalvarado@example.org
61         jodyvincent@example.org
62      hutchinsonkirk@example.com
65             maria32@example.org
68        daltoncalvin@example.net
69              ubanks@example.com
70         lopezdebbie@example.org
71            meagan39@example.net
75            wongmary@example.org
76          gailfrench@example.net
78              xpoole@example.net
79         cassandra80@example.org
81               nhall@example.net
82           erikaball@example.net
85              oblake@example.com
86     johnnyhendricks@example.net
87             pbarron@example.net
93           nicolas90@example.org
97            regina11@example.org
99           pcopeland@example.org
Name: Email, dtype: object

In [21]:
# Here the NaN are the blank Spaces.

In [22]:
people.dropna()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher
5,6,bfDD7CDEF5D865B,Erin,Day,Male,tconner@example.org,001-171-649-9856x5553,28-10-2015,Waste management officer
6,7,bE9EEf34cB72AF7,Katherine,Buck,Female,conniecowan@example.com,+1-773-151-6685x49162,22-01-1989,Intelligence analyst
...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,15-11-2016,IT sales professional

In [23]:
# Here the 5th index is missing now for dropna() function

In [24]:
people.fillna("Missing")

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Missing,bethany14@example.com,214.112.6044x4913,24-03-1910,Missing
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher
4,5,1bA7A3dc874da3c,Lori,Missing,Male,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,15-11-2016,IT sales professional

In [25]:
# Now the 5th Row Last Name Column is rewritten Missing but not changed the Original file. To change the Original File Use inplace = True in the function

In [26]:
people.rename(columns={"User Id" : "ID"})

,Index,ID,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,NaN,bethany14@example.com,214.112.6044x4913,24-03-1910,NaN
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher
4,5,1bA7A3dc874da3c,Lori,NaN,Male,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,15-11-2016,IT sales professional

### Change the DataType of any Column

In [27]:
people.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          100 non-null    int64
 1   User Id        100 non-null    object
 2   First Name     100 non-null    object
 3   Last Name      99 non-null     object
 4   Sex            99 non-null     object
 5   Email          100 non-null    object
 6   Phone          100 non-null    object
 7   Date of birth  100 non-null    object
 8   Job Title      99 non-null     object
dtypes: int64(1), object(8)
memory usage: 7.2+ KB

In [28]:
people["Index"] = people["Index"].astype(str)
people.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          100 non-null    object
 1   User Id        100 non-null    object
 2   First Name     100 non-null    object
 3   Last Name      99 non-null     object
 4   Sex            99 non-null     object
 5   Email          100 non-null    object
 6   Phone          100 non-null    object
 7   Date of birth  100 non-null    object
 8   Job Title      99 non-null     object
dtypes: object(9)
memory usage: 7.2+ KB

In [29]:
people["Index"] = people["Index"].astype("string")
people.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          100 non-null    string
 1   User Id        100 non-null    object
 2   First Name     100 non-null    object
 3   Last Name      99 non-null     object
 4   Sex            99 non-null     object
 5   Email          100 non-null    object
 6   Phone          100 non-null    object
 7   Date of birth  100 non-null    object
 8   Job Title      99 non-null     object
dtypes: object(8), string(1)
memory usage: 7.2+ KB

In [30]:
# Here str means the DataType as object so if want to make string then have to type 'string' in quotes

### ```len()``` function and adding column using pandas (Manually &  using Custom functions)

In [31]:
len(people)

100

In [32]:
people["manual_column"] = [0 for i in range(len(people))]
people

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title,manual_column
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer,0
1,2,f90cD3E76f1A9b9,Phillip,Summers,NaN,bethany14@example.com,214.112.6044x4913,24-03-1910,NaN,0
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath,0
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher,0
4,5,1bA7A3dc874da3c,Lori,NaN,Male,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon,0
...,...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer,0
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister,0
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer,0
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist,0
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,15-11-2016,IT sales professional,0

In [33]:
people["Index"] = people["Index"].astype(int)
def func(a):
    return a*a

people["function_column"] = people["Index"].apply(func)
people

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title,manual_column,function_column
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer,0,1
1,2,f90cD3E76f1A9b9,Phillip,Summers,NaN,bethany14@example.com,214.112.6044x4913,24-03-1910,NaN,0,4
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath,0,9
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher,0,16
4,5,1bA7A3dc874da3c,Lori,NaN,Male,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon,0,25
...,...,...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer,0,9216
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister,0,9409
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer,0,9604
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist,0,9801
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,15-11-2016,IT sales professional,0,10000

### Exporting the file as ```.csv``` file

In [44]:
people.to_csv("./data/pandas-people-export-1.csv", index=False) #Here if you do not do index = False, The iterations which genuinely start from 0 and go to len(file)-1 will also export which is not good, So use index = False in maximum cases

In [36]:
export_1 = pd.read_csv("./data/pandas-people-export-1.csv")
export_1

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title,manual_column,function_column
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,26-10-1945,Games developer,0,1
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,24-03-1910,NaN,0,4
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,02-07-1992,Homeopath,0,9
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,03-08-2017,Market researcher,0,16
4,5,1bA7A3dc874da3c,Lori,NaN,Male,buchananmanuel@example.net,689-207-3558x7233,01-12-1938,Veterinary surgeon,0,25
...,...,...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,30-07-1954,Software engineer,0,9216
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,29-04-1932,Barrister,0,9409
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,28-12-1994,Police officer,0,9604
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,12-04-2012,Broadcast journalist,0,9801
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,15-11-2016,IT sales professional,0,10000

### Concatenating DataFrames : When Want to make to DataFrames into One

In [37]:
dataFrame_1 = pd.DataFrame({"name":["Gojo" , "Geto" , "Shoko"], "marks":[100 , 90 , 80]})
dataFrame_2 = pd.DataFrame({"name":["Tanjiro" , "Zenitsu" , "Inosuke"] , "marks":[100 , 90 , 80]})

dataFrame_1

    name  marks
0   Gojo    100
1   Geto     90
2  Shoko     80

In [38]:
dataFrame_2

      name  marks
0  Tanjiro    100
1  Zenitsu     90
2  Inosuke     80

In [39]:
concat_dataFrame = pd.concat([dataFrame_1, dataFrame_2])
concat_dataFrame

      name  marks
0     Gojo    100
1     Geto     90
2    Shoko     80
0  Tanjiro    100
1  Zenitsu     90
2  Inosuke     80

### Merging DataFrames : Used to merger two data frames to get common data based on particular column

In [40]:
dataFrame_3 = pd.DataFrame({"name":["Gojo" , "Geto" , "Shoko" , "Sukuna"], "marks":[100 , 90 , 80 , 99]})
dataFrame_4 = pd.DataFrame({"name":["Gojo" , "Geto" , "Shoko"], "roll":[10 , 11 , 1]})

In [41]:
dataFrame_3

     name  marks
0    Gojo    100
1    Geto     90
2   Shoko     80
3  Sukuna     99

In [42]:
merged = pd.merge(dataFrame_3 , dataFrame_4 , on="name")
merged

    name  marks  roll
0   Gojo    100    10
1   Geto     90    11
2  Shoko     80     1

In [43]:
# 👆 Here Sukuna is not in the merged data